### ISSUE TITLE
Icon missing

### ISSUE THREAD

**Issue by NeroRome** [SecUSo/privacy-friendly-dame#10]
I've installed "Checkers" (Dame) form F-Droid but the icon is missing (in the launcher, in the apps-setting).
I've done it twice (since I've uninstalled it a few days ago) but i still have no icon. It's just a/the default Android-icon.

On all other PFA's I have an icon.

Device: Huawei P Smart, Android 8, EMUI 8.

**Comment by petermayer** [comment]
Hi, thanks for reporting this!
