### ISSUE TITLE
Fix movement behaviour of Kings

### ISSUE THREAD

**Issue by Telestrin** [SecUSo/privacy-friendly-dame#19]
Hello. I have very much been enjoying your checkers app, and it is *so close* to being perfec - but not quite. 

Unfortunately the Kings do not follow the rules for Standard Checkers - 1 square in any direction for movement or capture - and seem to be allowed unlimited capture and movement distance. This can be fun, but it is not the correct behavior. I would suggest changing them to match Standard Checkers rules, but at the very least could you please add an option to toggle this behavior ("Flying Kings") on or off, as I think this one quirk is ruining what is otherwise a stellar program

**Comment by sleep-yearning** [comment]
@Telestrin great to hear, that you like the app. Indeed it seems this behaviour is not in line with the common rules.
The issue has been added to our TODO list.
