### ISSUE TITLE
The black king piece turns White 

### ISSUE THREAD

**Issue by beckysophie** [SecUSo/privacy-friendly-dame#4]
***Actual Behavior***

After the other player's piece (black piece) has made it to the other player's territory and has become a king, on moving out of the cell and returning back to the cell, the black king pieced will automatically change its color to white 

***How to produce the bug***

 * open the app
 * Choose opponent, select human, and then select click on new game 

 * Keep playing the game, so as to make the black piece a king 

 * Move the black piece to the white player's territory 

 * Move it away from the white player's house 

 * Now come back in again.

* The black king piece will turn white 

***Recording of the bug is shown below......***

*Here's a video of everything......*

https://youtu.be/g-qyK6jUt5M

**Comment by Kamuno** [comment]
Fixed by #8
