### ISSUE TITLE
Enhancement of chekers by implementing some features 

### ISSUE THREAD

**Issue by cckole** [SecUSo/privacy-friendly-dame#6]
CHEKERS is a nice game. Why not add countdown time to Human(double player)? The delay on the part of opponent isn't encouraging... The countdown on each move to be made will hasten decisions and it will increase fast logical thinking....

It will also be Fantastic if different levels can be initiated as Hard bot, I've never been once defeated by the bot. It's too one sided... Need difficulty levels... Moreso, there is need for players to be able to set how they like the rules of the game to be, some love Capturing backward while some don't. This should be available to allow different people with different ways of playing to adopt it. 

The score count will be a very good plus to checkers. Players will find it easy to know how many times they've played and who got the highest victory.

Counting mistakes will not be made and there will be no argument on scores. It will also keep record of all the playing times players have had together.competing with other players(friend around) will be made easy with the score count implementation.

adding count down will be of great benefit. It will help to hasten players decision to make his moves on time.
The delay encountered from opponent will become expidited.
Gives player with the fastest move a motivation even though he lost to his opponent.
Lastly, please add a click sound.. Each move should produce a sound just like when checker is played manually. It will look more real and interesting.....

I will be glad if all these are implemented....hope you love the enhancement....Thanks for developing CHECKERS... 👑

**Comment by Kamuno** [comment]
Thank you for the great enhancement proposal.. I have split this Issue into multiple because you made quite a few proposals.. This issue will be closed.

This is now split into Issues #17 #16 #15 #14 #13
